# Generated by Django 4.0.8 on 2023-01-03 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FanPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token_page', models.CharField(blank=True, max_length=12288, null=True)),
                ('refresh_token_page', models.CharField(blank=True, max_length=12288, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=False, null=True)),
                ('app_secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_subscribe', models.DateTimeField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('facebook', 'Facebook')], default='facebook', max_length=30)),
                ('fanpage_user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(null=True)),
                ('page_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, max_length=10000, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='page_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fanPage_room', to='users.fanpage'),
        ),
    ]
