# Generated by Django 4.0.8 on 2022-12-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hotel_hotelroom_product_remove_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='rate_hotel',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='rate_hotel_room',
            field=models.IntegerField(blank=True, choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')], default=3),
        ),
    ]
